package com.example.TelegramBotAliexpress.enums;

public enum BotState {
    WAIT_STATUS,
    ADD_NEW_USER,
    ADD_USE_ACC_WITH_ORDERS,
    ADD_USE_ACC_WITH_ORDERS_TODAY,
    ADD_USE_ACC_WITHOUT_ORDERS,
    ADD_USE_ACC_WITHOUT_ORDERS_TODAY,
    DELETE_ACCOUNT,
    SELECT_PRICE,
    DELETE_ALL_ACC,
    SPLIT_ACCOUNTS
}
